### ISSUE TITLE
npm install failed out of the box...or did it?

### ISSUE THREAD

**Issue by mrichman** [coreui/coreui-free-bootstrap-admin-template#515]
I cloned your repo, ran `npm install` and it did this...I have no clue if it worked or not. I see `ERR!` which leads me to believe it failed, but I really can't tell.

```
npm install

> fsevents@1.2.9 install /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.8.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.3.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

> node-sass@4.13.1 install /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/darwin-x64-79_binding.node
Download complete ░⸩ ⠋ :
Binary saved to /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/node-sass/vendor/darwin-x64-79/binding.node
Caching binary to /Users/mark/.npm/node-sass/4.13.1/darwin-x64-79_binding.node

> core-js@2.6.9 postinstall /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.1 postinstall /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/node-sass/vendor/darwin-x64-79/binding.node
Testing binary
Binary is fine

> nodemon@2.0.2 postinstall /Users/mark/github.com/coreui/coreui-free-bootstrap-admin-template/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1587 packages from 700 contributors and audited 11324 packages in 39.227s

58 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm install  35.98s user 25.88s system 149% cpu 41.346 total
```

**Comment by mrichman** [comment]
Looks like I had to reinstall (for no apparent reason) the XCode command line tools.
